### PR TITLE
Example of debugging

### PR DESCRIPTION
**Pull request by usevalue**
This is what I have in mind.  Wanted your input before I go through with it.

### CODE REVIEW

**Comment by MarkehMe** [comment]
Maybe a better option would be to add a method into the Gringotts class so you can just go:

```
Gringotts.G.debug( .... )
```

and inside the debug method you can do something similar: 

```
public final void debug(String msg) {
    if (Configuration.CONF.debug) this.getLogger().log(Level.INFO, "[Debug] " + msg);
}
```

**Comment by usevalue** [comment]
That would be a bit cleaner, aye.

**Comment by jastice** [comment]
Hum, what do you think of just logging at actual debug level and using a logger config to append the output to a file at your preferred logging level (see https://bukkit.atlassian.net/browse/BUKKIT-5712)

**Comment by usevalue** [comment]
I don't quite understand what you're proposing.  From the link, I get the impression that it would take some fancy configuration work on the part of server admins.  As someone on the slightly competent end of the incompetence scale, I can't say I find that attractive, but, again, not sure I've understood.

**Comment by MarkehMe** [comment]
Simply put that would just required chucking some more information into the ```log4j2.xml``` file. :)

**Pull request closed without merging**
