### PR TITLE
Can it blend!? Making the project buildable again while tackling issues.

### PR DESCRIPTION
**Pull request by TheFlagCourier**
The primary goal of this PR was to fix (or at least give a foundation to fix) issues with the Towny integration. However, I sort of let it get away from me and ended up tackling more than that...

> Note: I do not personally use Gringotts, so these changes have not been tested in a production environment. However, I do believe it to be in a better state than the master branch currently is.

## Dependency Updates
* Update bStats (1.8), Towny (0.96.7.0), WorldEdit (7.2.2), and WorldGuard (7.0.4)
  * Use EngineHub's Repository over sk89q's
* Upgrade from JUnit4 to JUnit5 (JUnit Jupiter; 5.7.1)
* Remove zno.de repository and deployment scheme - Would run into HTTP 502 errors.

## Fixes
* Changed over to use Towny's new economy APIs. Breaks backwards compatibility with Towny versions prior.
  * In addition to updating Towny from 0.90.0.0 (which is _old_), most issues related to Towny should be resolved. 

## Deprecation & Removals
* Removed Migration class: Has no ill effect on a modern codebase, or servers since prior to [v2.10.1]
* Removed Apache Derby references, as well as DerbyDAO 
* Remove `Funding` file: Not enabled on this repository, repo has no active maintainers.

## Documentation
* Add Changelog entries for versions 2.10, 2.10.1, 2.11.0, and 2.11.1; Add `Pending Changes` entry to log changes to, prior to a tagged release. 
* Rewrite the `Maven/Gradle repo` section as `Depending on Gringotts` in the README
* Delimit LICENSE.txt to 80 characters in length.

### CODE REVIEW

**Comment by bundabrg** [comment]
Thanks. I'll have a look tomorrow.

**Comment by jastice** [comment]
Thanks for this! I'll let @nikosgram review and merge if he's still around ;)

> Remove zno.de repository and deployment scheme - Would run into HTTP 502 errors.

Probably because only I have the deployment keys. But if Jitpack works fine for this, no need to keep it around. I remember I had manually deployed some dependencies to repo.zno.de, maybe we can find an alternative for this as well?

**Comment by TheFlagCourier** [comment]
> Thanks for this! I'll let @nikosgram review and merge if he's still around ;)
> 
> > Remove zno.de repository and deployment scheme - Would run into HTTP 502 errors.
> 
> Probably because only I have the deployment keys. But if Jitpack works fine for this, no need to keep it around. I remember I had manually deployed some dependencies to repo.zno.de, maybe we can find an alternative for this as well?

I'm in no rush, so sounds good. Again, I don't personally use Gringotts, so if anyone sees something out of the ordinary, let me know.

Yeah, makes sense if the repository is locked away. If there is a need to manually deploy, then maybe using the GitHub Package Registry would be a good static replacement? Jitpack _can_ be finicky to work with, especially with a lack of recent release tags and as dependencies decay over time.

**Comment by jastice** [comment]
GitHub Package Registry sounds like a good idea. It wasn't around way back when.

**Comment by bundabrg** [comment]
Looks good so far but I'll just need to test on my server properly. Will get back soon.

**Comment by bundabrg** [comment]
Github package registry requires an account to read from so I tend to avoid it. I'm happy to provide deployment keys to my registry at https://repo.worldguard.com.au/ if you like @jastice otherwise jitpack isn't too bad generally.

**Comment by jastice** [comment]
shall we just merge this?

**Comment by TheFlagCourier** [comment]
@jastice It can be merged for current Towny compatibility. As a heads-up though, there are plans to nuke the Towny EconomyException (https://github.com/TownyAdvanced/Towny/pull/4806)

**Comment by jastice** [comment]
Thanks!

**Pull request merged**
